# Generated by Django 4.1.7 on 2023-03-26 13:40

import apps.posts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_businessman",
                    models.BooleanField(
                        default=True, verbose_name="является ли бизнесменом"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(verbose_name="Пост")),
                (
                    "phone_number",
                    models.CharField(
                        db_index=True,
                        help_text="Enter phone number in international format",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message='Phone number must be entered in the format: "+999999999". Up to 15 digits allowed.',
                                regex="^\\+(?:[0-9] ?){6,14}[0-9]$",
                            )
                        ],
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to=apps.posts.models.generate_filename),
                ),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
            },
        ),
    ]
