# Generated by Django 4.1.7 on 2023-03-28 16:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mail",
            name="user",
        ),
    ]
